###
# ```{rubric} Calico Values File
# ```
# ---
# Default values for template.
#
# This is a YAML-formatted file.
#
# Declare variables to be passed into your templates.
#
# ```{rubric} BGP
# ```
# ---
# Use this section to configure BGP.
#
# ```{literalinclude} /values.yaml
# :language: yaml
# :start-at: "bgp:\n"
# :end-before: "###\n"
# ```
bgp:
  peers:
  - name: calico-global-bgp-peer
    peerIP: 192.168.5.5
    asNumber: 209
    enableNodeToNodeMesh: true
  - name: hap01
    peerIP: 192.168.5.40
    asNumber: 65000
    enableNodeToNodeMesh: true
  - name: hap02
    peerIP: 192.168.5.50
    asNumber: 65000
    enableNodeToNodeMesh: true
  enabled: true

###
# ```{rubric} HAProxy
# ```
# ---
# This chart should allow for the configuration of an external HAProxy instance
# as a load balancer for the cluster.
#
# More information about how to do this is available
# [here](https://upto.site/4c767).
#
# ```{literalinclude} /values.yaml
# :language: yaml
# :start-at: "haproxy:\n"
# :end-before: "###\n"
# ```
haproxy:
  enabled: true
  controller:
    kind: DaemonSet
    ingressClass: haproxy
    service:
      type: LoadBalancer
      annotations:
        haproxy.org/standalone-backend: "true"
        service.beta.kubernetes.io/load-balancer-external: 192.168.5.40/24

###
# ```{rubric} HAProxy Ingress
# ```
# ---
# Enable and configure {term}`haproxy-ingress`.
#
# This is an in-cluster ingress controller, it does not integrate with external
# load balancers.
#
# ```{literalinclude} /values.yaml
# :language: yaml
# :start-at: "haproxy-ingress:\n"
# :end-before: "###\n"
# ```
haproxy-ingress:
  enabled: false
  # Expose HAProxy via a service loadbalancer
  controller:
    ingressClass: haproxy-ingress
    ingressClassResource:
      enabled: true

###
# ```{rubric} IP Pool
# ```
# ---
# Define IP pool objects here.
#
# ```{literalinclude} /values.yaml
# :language: yaml
# :start-at: "ippool:\n"
# :end-before: "###\n"
# ```
ippool:
  cidr: 10.0.0.0/8
  enabled: true
  name: calico-ip-pool

###
# ```{rubric} Override Release Name
# ```
# ---
# Use this section to configure BGP.
#
# ```{literalinclude} /values.yaml
# :language: yaml
# :start-at: "nameOverride: \"calico\""
# :end-before: "###\n"
# ```
nameOverride: "calico"

###
# ```{rubric} Status
# ```
# ---
# Use this section to configure status checks.
#
# ```{literalinclude} /values.yaml
# :language: yaml
# :start-at: "status:\n"
# :end-before: "###\n"
# ```
status:
  enabled: true
  name: calico-node-status
  node: kcp01.breeze-blocks.net

###
# ```{rubric} Testing
# ```
# ---
# Configure and enable testing.
#
# ```{literalinclude} /values.yaml
# :language: yaml
# :start-at: "testing:\n"
# ```
testing:
  enabled: false
