{{- range $.Values.bgp.peers }}
---
apiVersion: crd.projectcalico.org/v1
kind: BGPPeer
metadata:
  annotations:
    meta.helm.sh/release-name: calico
    meta.helm.sh/release-namespace: calico-system
  labels:
    app.kubernetes.io/name: calico
  name: {{ .name }}
spec:
  asNumber: {{ .asNumber }}
  peerIP: {{ .peerIP }}
{{ end }}
